### ISSUE TITLE
osTicket Docker

### ISSUE THREAD

**Issue by Not-Bruno** [osTicket/osTicket#6696]
When I create the osTicket under Docker behind an nginx reverse proxy, I get a bunch of php error messages. "php deprecated warning". These messages come with php8.0 to php8.3. However, when I use php7, I do not get these error messages. However, I cannot complete the setup as this version is no longer supported. 

I wrote the Docker image myself. I use a php:8.3-apache image as a basis and simply copy the data into the webroot directory. 

You can see the errors live here: https://temp.stadtverwaltung-wittenberg.de/

# Dockerfile

```
# Use the official PHP image as the base image
FROM php:8.3-apache

# Set environment variables for configuration
ENV OSTICKET_ZIP=osTicket_Plus_v1.18.1p1_full.zip \
    OSTICKET_CONF=ost-config.php \
    WEBSERVER_PATH=/var/www/html

COPY ./src/$OSTICKET_ZIP $WEBSERVER_PATH

# Install dependencies
RUN apt-get update && apt-get install unzip -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install -j$(nproc) \
    gd \
    mysqli \
    pdo \
    pdo_mysql \
    xml \
    zip

# Set the working directory
WORKDIR $WEBSERVER_PATH

RUN unzip $OSTICKET_ZIP
RUN mv upload/* ./ && rm $OSTICKET_ZIP
RUN rm -r upload && rm -r setup

# Copy the configuration file
COPY ./src/$OSTICKET_CONF ./include/ost-config.php

# Set the ownership and permissions
RUN chown -R www-data:www-data $WEBSERVER_PATH && chmod -R 755 $WEBSERVER_PATH

# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
```

# Docker Compose
```
version: "3.9"
services:

# Proxy
  proxy:
    image: "jwilder/nginx-proxy"
    container_name: "Proxy"
    restart: "always"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "prx_config:/etc/nginx/"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks: ["sys_net", "prj_net", "ncl_net", "kmb_net", "kee_net"]
    ports:
      - "443:443"
      - "80:80"

# Letsencrypt
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "LetsEncrypt"
    restart: "always"
    depends_on:
      proxy:
        condition: "service_started"
    volumes:
      - "prx_certs:/etc/nginx/certs"
      - "prx_vhost:/etc/nginx/vhost.d"
      - "prx_html:/usr/share/nginx/html"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "NGINX_PROXY_CONTAINER=Proxy"
    networks: ["sys_net"]

# osTicket
  osticket:
    image:  "osticket:1.18.1"
    container_name: "osTicket"
    restart: "always"
    depends_on:
      osticket_DB:
        condition: "service_healthy"
    environment:
      - "VIRTUAL_HOST=$VH_OSTICKET"
      - "LETSENCRYPT_HOST=$VH_OSTICKET"
    networks: ["ost_net"]

# osTicket DB
  osticket_DB:
    image: "mariadb"
    container_name: "osticket_DB"
    restart: "always"
    environment:
      - "MYSQL_USER=$OSTICKET_DB_USER"
      - "MYSQL_DATABASE=$OSTICKET_DB"
      - "MYSQL_ROOT_PASSWORD=$OSTICKET_DB_ROOT_PASSWORD"
    volumes:
      - "osticket_db_data:/var/lib/mysql"
    ports:
      - "3313:3306"
    networks: ["ost_net"]
    healthcheck:
      test: "mariadb --user=$OSTICKET_DB_USER --password=$OSTICKET_DB_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 1s
      retries: 10

networks:
# System
  sys_net: # 172.21.1.0/24
    name: "sys_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.1.0/24"
          ip_range: "172.21.1.0/24"
          gateway: "172.21.1.1"
# osTicket
  ost_net: # 172.21.14.0/24
    name: "ost_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.21.14.0/24"
          ip_range: "172.21.14.0/24"
          gateway: "172.21.14.1"

volumes:
  prx_certs: # CERTIFIKATE Proxy / Letsencrypt
    name: "prx_certs"
  prx_vhost: # VHOST Proxy / Letsencrypt
    name: "prx_vhost"
  prx_html: # HTML Proxy / Letsencrypt
    name: "prx_html"
  prx_config: # Configuration Proxy
    name: "prx_config"

  osticket_db_data: # osticket DB Data
    name: "osticket_db_data"
```
